name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Temporarily modify package.json
        run: |
          # Create a backup of the original package.json
          cp package.json package.json.bak

          # Remove the custom install script that uses Deno
          jq 'del(.scripts.install)' package.json > temp.json && mv temp.json package.json

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: npm install --no-scripts

      - name: Update next.config.ts for GitHub Pages
        run: |
          echo "// next.config.ts
          import { NextConfig } from 'next';

          const nextConfig: NextConfig = {
            output: 'export',
            basePath: process.env.GITHUB_ACTIONS && '/${GITHUB_REPOSITORY#*/}',
            images: {
              unoptimized: true,
            },
          };

          export default nextConfig;" > next.config.ts
      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Restore original package.json
        run: mv package.json.bak package.json

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
